### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nicholasklem** [garris/superSimpleExpressServer#1]
Hi!
Does this package come under a license to use? MIT or something compatible?
It showed up as a transitive dependency in our project, and we want to be sure we are able to use it.

Greetings
Nicholas

**Comment by garris** [comment]
Holy Mackerel -- Super sorry about that.  Just added MIT to the project -- thanks for letting me know.   This is just a really simple shim used inside BackstopJS.  Cheers!

**Comment by nicholasklem** [comment]
Super, thanks!

tor. 14. feb. 2019 kl. 18:06 skrev Garris <notifications@github.com>:
